<a href="https://colab.research.google.com/github/88FaHaD/Tensorflow/blob/main/Tensorflowbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [356]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [357]:
#creating tensors with tf.constant
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [358]:
# checking number of dimension in a tensor using ndim
scaler.ndim


0

In [359]:
# creating a vector with tf.constant
vector=tf.constant([7,10])
print(vector)
print(vector.ndim)

tf.Tensor([ 7 10], shape=(2,), dtype=int32)
1


In [360]:
# create a matrix
matrix=tf.constant([[10,7],
                    [7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


In [361]:
#create another matrix
vector2=tf.constant([[8,10],
                     [3.2,3.5],
                     [4.,5.]],dtype=tf.float16)
print(vector2)
print(vector2.ndim)

tf.Tensor(
[[ 8.  10. ]
 [ 3.2  3.5]
 [ 4.   5. ]], shape=(3, 2), dtype=float16)
2


In [362]:
# crating a tensor
tensor=tf.constant([[[2,3],
                     [4,5],
                     [6,8]]])
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[2 3]
  [4 5]
  [6 8]]], shape=(1, 3, 2), dtype=int32)
3


# creating tensors using tf.variable

In [363]:
# with tf.varible we create changable tensors
changable_tensor=tf.Variable([10,7])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [364]:
changable_tensor[0].assign(12)
print(changable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  7], dtype=int32)>


#CREATING RANDOM TENSORS

In [365]:
#normal distibution
random1=tf.random.Generator.from_seed(42)
random1=random1.normal(shape=(3,2),mean=5,stddev=1)
print(random1)

tf.Tensor(
[[4.2434196 4.9314528]
 [5.07595   3.7426157]
 [4.7680626 3.1892145]], shape=(3, 2), dtype=float32)


In [366]:
#uniform distribuution
random2=tf.random.Generator.from_seed(42)
random2=random2.uniform(shape=(3,2),minval=2,maxval=10)
print(random2)

tf.Tensor(
[[7.9947577 7.8849573]
 [5.6184635 5.9231853]
 [3.5114536 6.162202 ]], shape=(3, 2), dtype=float32)


# Shufling the order of elements in tensor

In [367]:
t1=tf.constant([[10,7],
                [3,4],
                [2,5]])
print(t1)


tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


In [368]:
#now using tf.shuffle
t2=tf.random.shuffle(t1,seed=42)
print(t2)

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


In [369]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [370]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Converting numpy arays into tensors

In [371]:
import numpy as np
numpy_array=np.arange(0,20)
print(numpy_array)
tensor = tf.constant(numpy_array, shape=(5,4))
tensor

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [372]:
tensor.ndim

2

#Geting Information from tensors
1 shape
2 rank
3 axis or dimension
4 size

In [373]:
rank4_tensor=tf.zeros(shape=[2,3,4,5])
print(rank4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [374]:
#Size
print(rank4_tensor.shape)

(2, 3, 4, 5)


In [375]:
#Rank
print(rank4_tensor.ndim)

4


In [376]:
#axis
print(rank4_tensor[0])

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)


In [377]:
print(tf.size(rank4_tensor))

tf.Tensor(120, shape=(), dtype=int32)


#Indexing and expanding tensors


In [378]:
# first 2 eleements of each dimension
print(rank4_tensor[:2,:2,:2,:2])

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [379]:
#get first element from each dimension from each index except final one
print(rank4_tensor[:1,:1,:1,])

tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


# Expanding a Tensor

In [380]:
rank2_tensor=tf.constant([[2,10],
                         [10,20]])
print(rank2_tensor)

tf.Tensor(
[[ 2 10]
 [10 20]], shape=(2, 2), dtype=int32)


In [381]:
rank2_tensor.shape


TensorShape([2, 2])

In [382]:
# geting last item of our rank 2 tensor
print(rank2_tensor[0,1],rank2_tensor[1,1])

tf.Tensor(10, shape=(), dtype=int32) tf.Tensor(20, shape=(), dtype=int32)


In [383]:
# # geting last item of our rank 2 tensor
print(rank2_tensor[:,1])

tf.Tensor([10 20], shape=(2,), dtype=int32)


In [384]:
#adding a new dimension
rank3_tensor=rank2_tensor[...,tf.newaxis]
print(rank3_tensor)

tf.Tensor(
[[[ 2]
  [10]]

 [[10]
  [20]]], shape=(2, 2, 1), dtype=int32)


In [385]:
rank3_tensor.shape

TensorShape([2, 2, 1])

In [386]:
rank3_tensor.ndim

3

In [387]:
tf.size(rank3_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [388]:
rank3_tensor[:,:,tf.newaxis]

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[ 2]],

        [[10]]],


       [[[10]],

        [[20]]]], dtype=int32)>

#Alternative way

In [389]:
tf.expand_dims(rank2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 2],
        [10]],

       [[10],
        [20]]], dtype=int32)>

In [390]:
tf.expand_dims(rank2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 2, 10],
        [10, 20]]], dtype=int32)>

# Tensor operations

In [391]:
tensor=tf.constant([[10,7],
                   [20,13]])
print(tensor)

tf.Tensor(
[[10  7]
 [20 13]], shape=(2, 2), dtype=int32)


In [392]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [30, 23]], dtype=int32)>

In [393]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [10,  3]], dtype=int32)>

In [394]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 5. ,  3.5],
       [10. ,  6.5]])>

In [395]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [40, 26]], dtype=int32)>

#Using built in tensor math methods

In [396]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [200, 130]], dtype=int32)>

In [397]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [30, 23]], dtype=int32)>

In [398]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [10,  3]], dtype=int32)>

In [399]:
tf.divide(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [2. , 1.3]])>

#Matrix Multiplication

In [400]:
tensor1=tf.constant([[[1,2,5],
                      [7,2,1],
                      [3,3,3]]])
tensor2=tf.constant([[3,5],
                     [6,7],
                     [1,8]])

In [401]:
tensor3=tf.matmul(tensor1,tensor2)
tensor3

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [402]:
tensor1=tf.constant([[3,5],
                     [6,7],
                     [1,8]])
tensor2=tf.constant([[[1,2,5],
                      [7,2,1],
                      [3,3,3]]])

# Note
 For matrix multiplication to be valid, the last dimension of the first tensor must match the second-to-last dimension of the second tensor.

In [403]:
tensor1=tf.reshape(tensor1,(2,3))

In [404]:
tensor3=tf.matmul(tensor1,tensor2)
tensor3

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[56, 34, 38],
        [38, 40, 60]]], dtype=int32)>

#Transpose

In [405]:
tensor1=tf.constant([[3,5],
                     [6,7],
                     [1,8]])
tensor2=tf.constant([[1,2,5],
                     [7,2,1],
                     [3,3,3]])


In [406]:
tensor3=tf.matmul(tf.transpose(tensor1),tensor2)
tensor3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 21, 24],
       [78, 48, 56]], dtype=int32)>

# Using tensordot

In [407]:
tensor4=tf.tensordot(tf.transpose(tensor1),tensor2,axes=1)
print(tensor4)

tf.Tensor(
[[48 21 24]
 [78 48 56]], shape=(2, 3), dtype=int32)


# Changing datatype of tensors

In [408]:
t1=tf.constant([1.7,7.4])
t1.dtype

tf.float32

In [409]:
t2=tf.constant([1,7])
t2.dtype

tf.int32

In [410]:
t1=tf.cast(t1,dtype=tf.float16)
t1.dtype

tf.float16

In [411]:
t2=tf.cast(t2,dtype=tf.int16)
t2.dtype

tf.int16

#Tensor agregation


In [412]:
tensor=tf.constant([-7,-10])
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [413]:
tensor=tf.random.Generator.from_seed(42)
tensor_uniform=tensor.uniform(shape=(50,3),minval=1,maxval=150)


In [414]:
tensor_uniform

<tf.Tensor: shape=(50, 3), dtype=float32, numpy=
array([[112.65236  , 110.60733  ,  68.39388  ],
       [ 74.06933  ,  29.150824 ,  78.52101  ],
       [131.17952  ,  70.91336  ,  96.25955  ],
       [ 97.36005  , 144.40767  ,  62.103653 ],
       [129.94571  , 133.05838  ,  42.41564  ],
       [132.98067  ,  33.479645 ,  44.381523 ],
       [  6.8912544, 122.23818  , 122.2838   ],
       [ 78.74922  ,  19.620417 ,  82.77839  ],
       [116.56102  ,  93.1476   ,  38.154972 ],
       [134.11934  ,  43.350037 , 105.79565  ],
       [ 40.069843 ,  67.039215 ,  70.50328  ],
       [  9.9129925,  60.746323 , 104.245605 ],
       [ 20.14179  ,  34.92785  ,  51.199913 ],
       [ 80.40416  ,  89.12345  ,  33.389984 ],
       [ 80.29892  ,   8.671025 ,   6.8876133],
       [ 63.381645 , 118.620476 ,   7.532576 ],
       [145.4642   ,  74.18311  ,  56.222363 ],
       [ 50.967743 ,   5.113651 , 149.63869  ],
       [ 78.737404 ,  31.257685 , 108.01995  ],
       [126.55273  , 143.18466  , 135.2

In [415]:
#minimum
tf.reduce_min(tenosr_uniform)

<tf.Tensor: shape=(), dtype=float32, numpy=5.113651>

In [416]:
# maximum
tf.reduce_max(tenosr_uniform)

<tf.Tensor: shape=(), dtype=float32, numpy=149.63869>

In [417]:
#mean
tf.reduce_mean(tensor_uniform)

<tf.Tensor: shape=(), dtype=float32, numpy=73.38279>

In [418]:
#sum
tf.reduce_sum(tensor_uniform)

<tf.Tensor: shape=(), dtype=float32, numpy=11007.419>

In [419]:
#variance
tf.math.reduce_variance(tensor_uniform)

<tf.Tensor: shape=(), dtype=float32, numpy=1571.7205>

In [420]:
#standard deviation
tf.math.reduce_std(tensor_uniform)

<tf.Tensor: shape=(), dtype=float32, numpy=39.644928>

#Finding positional minimum and maximum

In [421]:
tf.random.set_seed(42)
tensor=tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [422]:
tf.argmax(tensor) # gives the postional value

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [423]:
tensor[tf.argmax(tensor)] #gives the value which is present t that position

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [424]:
tf.reduce_max(tensor) # gives the value at thatcpositon

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [425]:
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [426]:
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [427]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# squeezing a tensor

In [428]:
tensor=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [429]:
tensor_squeezed=tf.squeeze(tensor)
tensor_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

#One hot encoding

In [430]:
listtt=[0,1,2,3,4]
tf.one_hot(listtt,depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

# SOME MORE TENSOR OPERATIONS

In [431]:
tensor=tf.range(1,10)
tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [432]:
tf.square(tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [433]:
tensor=tf.cast(tensor,dtype=tf.float32)

In [434]:
tf.sqrt(tensor)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [435]:
tf.math.log(tensor)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#Convertng a numpy array to tensor

In [436]:
a=tf.constant(np.array([3.,7.,10.]))
a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [437]:
b=np.array(tf.constant([2,3,4,5]))
b

array([2, 3, 4, 5], dtype=int32)